CREATE TABLE Item1 (
    id INTEGER NOT NULL,
    data VARCHAR(50) NOT NULL,
    CONSTRAINT PK_Item1 PRIMARY KEY(id)
)

INSERT INTO Item1 (data) VALUES ("go shopping");
INSERT INTO Item1 (data) VALUES ("sleeping");

GRANT SELECT ON Item1 TO SQL-EDU-01;

REVOKE SELECT ON Item1 FROM SQL-EDU-01;

CREATE ROLE friend_role_01;

GRANT SELECT, INSERT ON Item1 TO friend_role_01;

ALTER ROLE friend_role_01 ADD MEMBER SQL-EDU-01;

REVOKE INSERT ON Item1 FROM friend_role_01;

ALTER ROLE friend_role_01 DROP MEMBER SQL-EDU-O1;

DROP ROLE friend_role_01;
